name: Deploy Lambda

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy-lambda:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: GOARCH=amd64 GOOS=linux go build -o bootstrap main.go
      - run: zip lambda.zip bootstrap
      - uses: yvesgurcan/deploy-lambda-function@master
        with:
          package: lambda.zip
          function-name: main
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
